### ISSUE TITLE
Failed to synchronize

### ISSUE THREAD

**Issue by brenoperucchi** [agiliumtrade-ai/metaapi-python-sdk#4]
I was following the example at:

```
/metaapi-python-sdk/examples/mt5/metaApiSynchronizationExample.py/
```

show me this error:
```
❯ python3 metaapi.py
Waiting for API server to connect to broker (may take couple of minutes)
Waiting for SDK to synchronize to terminal state (may take some time depending on your history size)
[2021-04-27T21:32:41.739117] MetaApi websocket client connected to the MetaApi server
[2021-04-27T21:32:42.762184] MetaApi websocket client for account 477e6b85-e17c-4a8b-9362-2a2c810fc1cd:0 failed to synchronize year 53269 is out of range
[2021-04-27T21:32:44.765503] MetaApi websocket client for account 477e6b85-e17c-4a8b-9362-2a2c810fc1cd:0 failed to synchronize year 53269 is out of range
```

```python
import os
import asyncio
from metaapi_cloud_sdk import MetaApi

from metaapi_cloud_sdk.clients.metaApi.tradeException import TradeException
# Note: for information on how to use this example code please read https://metaapi.cloud/docs/client/usingCodeExamples


token = 'Xxx'
accountId = '477e6b85-e17c-4a8b-9362-2a2c810fc1cd'



async def test_meta_api_synchronization():
    api = MetaApi(token)
    try:
        # Add test MetaTrader account
        account = await api.metatrader_account_api.get_account(accountId)
        print('Waiting for API server to connect to broker (may take couple of minutes)')
        await account.wait_connected()

        # connect to MetaApi API
        connection = await account.connect()

        # wait until terminal state synchronized to the local state
        print('Waiting for SDK to synchronize to terminal state (may take some time depending on your history size)')
        await connection.wait_synchronized({'timeoutInSeconds': 600})
```

**Comment by RomanKisilenko** [comment]
Try to remove the .metaapi folder (located in the directory you run the example from) and retry. Please let me know if your example executes correctly after that.

**Comment by brenoperucchi** [comment]
now I have a TimeoutException error. 

```
{'name': 'TimeoutException', 'message': 'Timed out waiting for MetaApi to synchronize to MetaTrader account 477e6b85-e17c-4a8b-9362-2a2c810fc1cd, synchronization id None', 'trace': 'Traceback (most recent call last):\n  File "api.py", line 27, in test_meta_api_synchronization\n    await connection.wait_synchronized({\'timeoutInSeconds\': 600})\n  File "/usr/local/lib/python3.8/site-packages/metaapi_cloud_sdk/metaApi/metaApiConnection.py", line 999, in wait_synchronized\n    raise TimeoutException(\'Timed out waiting for MetaApi to synchronize to MetaTrader account \' +\nmetaapi_cloud_sdk.clients.timeoutException.TimeoutException: Timed out waiting for MetaApi to synchronize to MetaTrader account 477e6b85-e17c-4a8b-9362-2a2c810fc1cd, synchronization id None\n'}
```

**Comment by RomanKisilenko** [comment]
I'm able to synchronize to your account successfully. Please contact support via online chat to get assistance from our team as your issue most likely is not a bug in python sdk code.

**Comment by devtrap** [comment]
How we should contact via online chat?
